<?php

namespace AppBundle\Repository;

/**
 * AfficheCARepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AfficheCARepository extends \Doctrine\ORM\EntityRepository
{
}
